FROM ubuntu:16.04

RUN apt-get dist-upgrade
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt-get install -y git openjdk-8-jdk python3.6 python3-pip build-essential libssl-dev libffi-dev libxml2-dev libxslt1-dev zlib1g-dev python3.6-dev python3.6-venv gettext

RUN pip3 install pipenv

WORKDIR /home

RUN git clone https://github.com/akramkazmi71/nth-fibonacci-api

WORKDIR /home/nth-fibonacci-api

RUN pip3 install -r requirements.txt
RUN python3 --version

RUN pip3 install django --upgrade

EXPOSE 8080

ENTRYPOINT ["python3", "manage.py"]
CMD ["runserver", "0.0.0.0:8000"]

