# Generated by Django 2.2.6 on 2019-10-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='top_speed',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
