# Generated by Django 2.2.6 on 2019-10-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191023_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
