# Generated by Django 2.2.6 on 2019-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonacci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
    ]
