# Generated by Django 2.2.6 on 2019-10-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_fibonacci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fibonacci',
        ),
    ]
